### ISSUE TITLE
How to improve confidence or reduce variance

### ISSUE THREAD

**Issue by pr0g** [sheredom/ubench.h#13]
Hello there!

I've been having a little play around with `ubench.h` but have run into the problem where my benchmarks exceed the default confidence threshold by some margin (they're usually between 20% and 30%).

Is there any way to improve this without having to just said a high confidence threshold? For example, say I wanted to profile something like `push_back` in a custom vector with the `std::vector` implementation. Would increasing the number of iterations help (and I imagine calling `reserve` first to reduce any spikes). Or should a single call suffice and `ubench.h` internally figures out how many iterations are needed?

Thanks very much for your time

Tom

**Comment by sheredom** [comment]
Hey Tom!

Basically it'll try and raise the number of iterations up to some cutoff until it gets a confidence interval that is low enough.

It'll do at most 500 iterations though - and so it could be that you've got too little work in the body of the benchmark? Maybe try perform 1000 pushes instead of a single one?

**Comment by pr0g** [comment]
Hey Neil!

Ah okay I see, I've tried increasing the number of iterations as you suggested but that seems to have made the confidence interval worse 😬

I've got something that looks like this...

```c++
struct fixture_t {
  size_t iterations = 0;
  std::vector<int> container;
};

UBENCH_F_SETUP(fixture_t) {
  ubench_fixture->iterations = 1000;
  ubench_fixture->container.reserve(ubench_fixture->iterations);
}
UBENCH_F_TEARDOWN(fixture_t) { 
  std::vector<int>().swap(ubench_fixture->container);
}
UBENCH_F(fixture_t, push_back) { 
  for (size_t i = 0; i < ubench_fixture->iterations; ++i) {
    ubench_fixture->container.push_back(i);
  }
}
```

With an iteration count of 1, the confidence interval is 10.4%. With 100 iterations it's 20.7% and with 1000 it's 27.6%

Apologies if there's something I'm missing, I just wanted to check if there was a way to get the confidence interval down to the 2.5% that's recommended.

Thanks for your help!

Tom

**Comment by sheredom** [comment]
Thanks for the code sample - honestly I'm really **not sure** why the confidence interval is so bad the more I look. The results from the benchmark are super spiky, which I can only put down to power management or something like that in the OS (because you've done the reserve, no malloc/new gets hit and it should be blindingly fast!).

I think the one issue I can think of is that most of my benchmarks where I've used `ubench.h` are in the 10ms+ range, and I guess that when I'm dealing with workloads as large as that there is much less deviation between subsequent runs - only thing I can think of though.

**Comment by pr0g** [comment]
Thanks for getting back to me @sheredom. I'm running them on a pretty old MacBook so it's possible that isn't helping much either 🙈

That's cool no problem, I'll try it out with a different sort of workload in future and let you know how it goes.

Thanks for your time!

Tom
