### ISSUE TITLE
Is there an option to remove the output of the code being benchmarked

### ISSUE THREAD

**Issue by LazyHippogriff** [sheredom/ubench.h#2]
Thanks for your support earlier. When I ran the benchmark on the functions:
 ```
 UBENCH(func1,using_cout) {
  cout<<"Hello World"<<endl;
  }

  UBENCH(func2,using_printf) {
  printf("Hello World\n");
  }
```

I get a lot of output on the screen due to several runs of the functions. As a result, the result of the first benchmark(func1) was hidden in between a lot of text. Is there an option to remove all the output of the code being benchmarked so that I see only the benchmark results? Or maybe get the summarised results of all the benchmarks in the end?
Also is there a way to control the number of runs/ tweak the allowed standard deviation?

**Comment by sheredom** [comment]
No option for the output. But you can use --output=foo.csv and then cat the file perhaps?

I just (in https://github.com/sheredom/ubench.h/pull/3) removed the ability change the standard deviation because I realised I should be using the confidence interval instead. It'd let you do `--confidence=2.0` to say that 2% is the exceptable divergence from the mean.

RE the number of runs - not yet. I've just (again in https://github.com/sheredom/ubench.h/pull/3) changed it so that the default iterations run is determined by the time taken to run the benchmark (I run it once to gauge the time).
